{{-- 通知履歴モーダル（共通パーシャル） --}}
<div id="notifLogModal" style="display:none; position:fixed; inset:0; z-index:9999; background:rgba(0,0,0,0.5); overflow-y:auto;">
    <div style="max-width:700px; margin:40px auto; background:#fff; border-radius:12px; box-shadow:0 8px 32px rgba(0,0,0,0.15); font-family:'Noto Sans JP',sans-serif;">
        <div style="display:flex; justify-content:space-between; align-items:center; padding:16px 20px; border-bottom:1px solid #e8e0d4;">
            <div>
                <h3 style="margin:0; font-size:16px; color:#5c4a3a;" id="notifLogTitle">通知履歴</h3>
                <span style="font-size:12px; color:#8b7b6b;" id="notifLogSubtitle"></span>
            </div>
            <button onclick="closeNotifLogModal()" style="background:none; border:none; font-size:24px; color:#8b7b6b; cursor:pointer; padding:0 4px;">&times;</button>
        </div>
        <div style="display:flex; border-bottom:1px solid #e8e0d4;">
            <button id="tabAiCall" onclick="switchNotifTab('aiCall')" style="flex:1; padding:10px; border:none; background:#f5f0e8; font-size:13px; font-weight:600; color:#5c4a3a; cursor:pointer; border-bottom:2px solid #a08060;">AIコール履歴</button>
            <button id="tabNotif" onclick="switchNotifTab('notif')" style="flex:1; padding:10px; border:none; background:#faf7f2; font-size:13px; font-weight:600; color:#8b7b6b; cursor:pointer; border-bottom:2px solid transparent;">メール・SMS通知</button>
        </div>
        <div id="notifLogContent" style="padding:16px 20px; min-height:200px;">
            <div style="text-align:center; color:#8b7b6b; padding:40px;">読み込み中...</div>
        </div>
    </div>
</div>
<style>
.notif-log-table{width:100%;border-collapse:collapse;font-size:13px}.notif-log-table th{background:#f5f0e8;color:#5c4a3a;font-weight:600;padding:8px 10px;text-align:left;border-bottom:1px solid #e8e0d4;white-space:nowrap}.notif-log-table td{padding:8px 10px;border-bottom:1px solid #f0ebe3;color:#5c4a3a;vertical-align:top}.notif-log-table tr:hover{background:#faf7f2}.notif-badge{display:inline-block;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:600}.notif-badge-good{background:#d4edda;color:#155724}.notif-badge-check{background:#fff3cd;color:#856404}.notif-badge-alert{background:#f8d7da;color:#721c24}.notif-badge-unclear{background:#e2e3e5;color:#383d41}.notif-badge-completed{background:#d4edda;color:#155724}.notif-badge-no_answer{background:#fff3cd;color:#856404}.notif-badge-failed{background:#f8d7da;color:#721c24}.notif-badge-sent{background:#d4edda;color:#155724}.notif-badge-pending{background:#fff3cd;color:#856404}.notif-summary{display:flex;gap:16px;margin-bottom:12px;flex-wrap:wrap}.notif-summary-item{background:#f5f0e8;padding:8px 14px;border-radius:8px;font-size:13px;color:#5c4a3a}.notif-summary-item strong{font-size:18px;display:block;margin-top:2px}.notif-transcript{max-width:200px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;cursor:pointer}.notif-transcript:hover{white-space:normal;word-break:break-all}.notif-log-trigger{display:inline-flex;align-items:center;gap:3px;cursor:pointer;padding:2px 6px;border-radius:4px;font-size:11px;color:#8b7b6b;border:1px solid #e8e0d4;background:#faf7f2;transition:background 0.15s}.notif-log-trigger:hover{background:#f0ebe3;color:#5c4a3a}.notif-log-trigger svg{width:13px;height:13px}
</style>
<script>
let notifLogData=null;let currentNotifTab='aiCall';
function openNotifLogModal(deviceId,label){const modal=document.getElementById('notifLogModal');modal.style.display='block';document.getElementById('notifLogTitle').textContent='通知履歴';document.getElementById('notifLogSubtitle').textContent=label||deviceId;document.getElementById('notifLogContent').innerHTML='<div style="text-align:center;color:#8b7b6b;padding:40px;">読み込み中...</div>';currentNotifTab='aiCall';updateTabStyles();let url;if(typeof notifLogBaseUrl!=='undefined'&&notifLogBaseUrl){url=notifLogBaseUrl;}else if(window.location.pathname.startsWith('/partner/org')){url='/partner/org/devices/'+deviceId+'/notification-logs';}else if(window.location.pathname.startsWith('/partner')){url='/partner/devices/'+deviceId+'/notification-logs';}else{url='/mypage/notification-logs';}fetch(url,{headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json'}}).then(r=>r.json()).then(data=>{notifLogData=data;renderNotifTab();}).catch(err=>{document.getElementById('notifLogContent').innerHTML='<div style="text-align:center;color:#c0392b;padding:40px;">読み込みに失敗しました</div>';});}
function closeNotifLogModal(){document.getElementById('notifLogModal').style.display='none';notifLogData=null;}
function switchNotifTab(tab){currentNotifTab=tab;updateTabStyles();renderNotifTab();}
function updateTabStyles(){const a=document.getElementById('tabAiCall');const b=document.getElementById('tabNotif');if(currentNotifTab==='aiCall'){a.style.background='#f5f0e8';a.style.color='#5c4a3a';a.style.borderBottom='2px solid #a08060';b.style.background='#faf7f2';b.style.color='#8b7b6b';b.style.borderBottom='2px solid transparent';}else{b.style.background='#f5f0e8';b.style.color='#5c4a3a';b.style.borderBottom='2px solid #a08060';a.style.background='#faf7f2';a.style.color='#8b7b6b';a.style.borderBottom='2px solid transparent';}}
function renderNotifTab(){if(!notifLogData)return;const c=document.getElementById('notifLogContent');if(currentNotifTab==='aiCall'){renderAiCallTab(c);}else{renderNotifLogTab(c);}}
function renderAiCallTab(c){const logs=notifLogData.ai_call_logs||[];const count=notifLogData.ai_call_count||0;let h='<div class="notif-summary"><div class="notif-summary-item">AIコール回数<strong>'+count+'回</strong></div></div>';if(logs.length===0){h+='<div style="text-align:center;color:#8b7b6b;padding:30px;">AIコール履歴はありません</div>';c.innerHTML=h;return;}h+='<div style="overflow-x:auto;"><table class="notif-log-table"><thead><tr><th>発信日時</th><th>種別</th><th>通話結果</th><th>AI判定</th><th>通話時間</th><th>発言内容</th></tr></thead><tbody>';logs.forEach(function(l){const sl={'completed':'応答','no_answer':'不在','failed':'失敗'}[l.call_status]||l.call_status;const sc='notif-badge notif-badge-'+l.call_status;const jl={'good':'元気','check':'要確認','alert':'異常','unclear':'判定不能'}[l.judgment]||'-';const jc=l.judgment?'notif-badge notif-badge-'+l.judgment:'';const d=l.duration_sec?l.duration_sec+'秒':'-';const t=l.transcript||'-';h+='<tr><td style="white-space:nowrap;">'+(l.called_at||'-')+'</td><td>'+(l.direction==='inbound'?'折り返し':'発信')+'</td><td><span class="'+sc+'">'+sl+'</span></td><td>'+(l.judgment?'<span class="'+jc+'">'+jl+'</span>':'-')+'</td><td>'+d+'</td><td class="notif-transcript" title="'+escNotif(t)+'">'+escNotif(t)+'</td></tr>';});h+='</tbody></table></div>';c.innerHTML=h;}
function renderNotifLogTab(c){const logs=notifLogData.notification_logs||[];if(logs.length===0){c.innerHTML='<div style="text-align:center;color:#8b7b6b;padding:30px;">通知履歴はありません</div>';return;}let h='<div style="overflow-x:auto;"><table class="notif-log-table"><thead><tr><th>日時</th><th>種別</th><th>チャンネル</th><th>送信先</th><th>結果</th></tr></thead><tbody>';const tl={'alert':'未検知','offline':'通信途絶','battery_low':'電池低下','test':'テスト','system':'システム'};const cl={'email':'メール','sms':'SMS','webpush':'Webプッシュ','voice':'音声通話'};const stl={'sent':'送信済','failed':'失敗','pending':'処理中'};logs.forEach(function(l){h+='<tr><td style="white-space:nowrap;">'+(l.created_at||'-')+'</td><td>'+(tl[l.type]||l.type)+'</td><td>'+(cl[l.channel]||l.channel)+'</td><td style="max-width:160px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">'+escNotif(l.recipient||'-')+'</td><td><span class="notif-badge notif-badge-'+(l.status||'')+'">'+(stl[l.status]||l.status)+'</span></td></tr>';});h+='</tbody></table></div>';c.innerHTML=h;}
function escNotif(s){if(!s)return'';return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
document.getElementById('notifLogModal').addEventListener('click',function(e){if(e.target===this)closeNotifLogModal();});
</script>