name: Deploy to XServer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to XServer
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
		script: |
			            cd ${{ secrets.DEPLOY_PATH }}
			            git pull origin main
			            /opt/php-8.4.12/bin/php artisan config:cache
			            /opt/php-8.4.12/bin/php artisan route:cache
			            /opt/php-8.4.12/bin/php artisan view:clear